### ISSUE TITLE
Unexpected keyword argument gpgbinary on running

### ISSUE THREAD

**Issue by GijsTimmers** [quulah/pass2bitwarden#3]
Hello,

Thanks for taking the time to write this script and share it. I get an error immediately after running it:
```
$ python3 pass2bw.py 
Traceback (most recent call last):
  File "pass2bw.py", line 120, in <module>
    main()
  File "pass2bw.py", line 112, in main
    decrypted_files = decrypt(encrypted_files, args.binary, args.agent)
  File "pass2bw.py", line 32, in decrypt
    gpg = gnupg.GPG(gpgbinary=binary,
TypeError: __init__() got an unexpected keyword argument 'gpgbinary'
```

**Comment by quulah** [comment]
My first guess would be that something has changed in the gnupg library used.

**Comment by quulah** [comment]
Or do you happen to have some different library installed that gets imported?

`gpgbinary` seems to be here at least: https://github.com/vsajip/python-gnupg/blob/ba0bb50692a1b32ac78f01faf744b9133120a4ed/gnupg.py#L877

:)

**Comment by GijsTimmers** [comment]
I installed the wrong binary;

I issued:

`pip install gnupg`

You should issue:

`pip install python-gnupg`
